12*2.monaco-list.list_id_1:focus .monaco-list-row.focused { background-color: #dcebfc; }
.monaco-list.list_id_1:focus .monaco-list-row.focused:hover { background-color: #dcebfc; }
.monaco-list.list_id_1:focus .monaco-list-row.selected { background-color: #52a8ff; }
.monaco-list.list_id_1:focus .monaco-list-row.selected:hover { background-color: #52a8ff; }
.monaco-list.list_id_1:focus .monaco-list-row.selected { color: #ffffff; }
.monaco-list.list_id_1:focus .monaco-list-row.selected.focused { background-color: #3399ff; }
.monaco-list.list_id_1:focus .monaco-list-row.selected.focused { color: #ffffff; }
.monaco-list.list_id_1 .monaco-list-row.focused { background-color:  #dcebfc; }
.monaco-list.list_id_1 .monaco-list-row.focused:hover { background-color:  #dcebfc; }
.monaco-list.list_id_1 .monaco-list-row.selected { background-color:  #cccedb; }
.monaco-list.list_id_1 .monaco-list-row.selected:hover { background-color:  #cccedb; }
.monaco-list.list_id_1 .monaco-list-row:hover { background-color:  #f0f0f0; }